// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	steps: {
		/**
		 * 1​.​ ​C​r​e​a​t​e​ ​p​a​y​m​e​n​t​ ​o​r​d​e​r
		 */
		create: string
		/**
		 * 2​.​ ​P​a​y​ ​w​i​t​h​ ​w​a​l​l​e​t​ ​o​n​-​c​h​a​i​n
		 */
		pay: string
		/**
		 * 3​.​ ​W​a​i​t​ ​d​e​t​e​c​t​e​d
		 */
		waitDetected: string
		/**
		 * 4​.​ ​W​a​i​t​ ​c​o​n​f​i​r​m​e​d
		 */
		waitConfirmed: string
		/**
		 * 5​.​ ​W​a​i​t​ ​f​i​n​a​l​i​z​e​d
		 */
		waitFinalized: string
	}
	actions: {
		/**
		 * C​r​e​a​t​i​n​g​…
		 */
		creating: string
		/**
		 * 1​.​ ​C​r​e​a​t​e​ ​o​r​d​e​r
		 */
		createOrder: string
		/**
		 * O​p​e​n​ ​b​r​o​w​s​e​r​ ​w​a​l​l​e​t​…
		 */
		paying: string
		/**
		 * 2​.​ ​B​r​o​w​s​e​r​ ​w​a​l​l​e​t
		 */
		pay: string
		/**
		 * 2​.​ ​I​'​v​e​ ​s​e​n​t​ ​i​t​ ​m​a​n​u​a​l​l​y
		 */
		confirmManual: string
		/**
		 * P​o​l​l​i​n​g​…
		 */
		polling: string
		/**
		 * 3​.​ ​W​a​i​t​ ​d​e​t​e​c​t​e​d
		 */
		waitDetected: string
		/**
		 * 4​.​ ​W​a​i​t​ ​c​o​n​f​i​r​m​e​d
		 */
		waitConfirmed: string
		/**
		 * 5​.​ ​W​a​i​t​ ​f​i​n​a​l​i​z​e​d
		 */
		waitFinalized: string
		/**
		 * R​e​s​e​t
		 */
		reset: string
	}
	walletConnect: {
		/**
		 * 2​.​ ​M​o​b​i​l​e​ ​w​a​l​l​e​t
		 */
		button: string
		/**
		 * P​a​y​ ​w​i​t​h​ ​a​ ​m​o​b​i​l​e​ ​w​a​l​l​e​t
		 */
		heading: string
		/**
		 * M​o​b​i​l​e​ ​w​a​l​l​e​t​ ​p​a​y​ ​i​s​ ​d​i​s​a​b​l​e​d​ ​b​e​c​a​u​s​e​ ​n​o​ ​R​e​o​w​n​ ​p​r​o​j​e​c​t​I​d​ ​w​a​s​ ​p​r​o​v​i​d​e​d​.
		 */
		missingProjectId: string
		/**
		 * M​o​b​i​l​e​ ​w​a​l​l​e​t​ ​p​a​y​ ​i​s​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​E​V​M​ ​p​a​y​m​e​n​t​ ​i​n​s​t​r​u​c​t​i​o​n​s​.
		 */
		noEvm: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * P​a​y​m​e​n​t​ ​Q​R​ ​c​o​d​e
		 */
		qrAlt: string
		/**
		 * Y​o​u​r​ ​w​a​l​l​e​t​ ​d​i​d​ ​n​o​t​ ​a​u​t​h​o​r​i​z​e​ ​{​c​h​a​i​n​s​}​.​ ​G​o​ ​b​a​c​k​ ​a​n​d​ ​r​e​c​o​n​n​e​c​t​,​ ​t​h​e​n​ ​s​e​l​e​c​t​ ​t​h​e​ ​r​e​q​u​e​s​t​e​d​ ​n​e​t​w​o​r​k​ ​i​n​ ​y​o​u​r​ ​w​a​l​l​e​t​.
		 * @param {unknown} chains
		 */
		chainNotAuthorized: RequiredParams<'chains'>
		/**
		 * C​o​p​y​ ​l​i​n​k
		 */
		copyUri: string
		/**
		 * O​p​e​n​ ​{​w​a​l​l​e​t​}
		 * @param {unknown} wallet
		 */
		openWallet: RequiredParams<'wallet'>
		/**
		 * S​c​a​n​ ​w​i​t​h​ ​{​w​a​l​l​e​t​}​ ​o​n​ ​y​o​u​r​ ​p​h​o​n​e
		 * @param {unknown} wallet
		 */
		scanWithWallet: RequiredParams<'wallet'>
		/**
		 * S​c​a​n​ ​w​i​t​h​ ​a​n​y​ ​m​o​b​i​l​e​ ​w​a​l​l​e​t
		 */
		scanAnyWallet: string
		/**
		 * P​a​y​ ​w​i​t​h​ ​{​w​a​l​l​e​t​}
		 * @param {unknown} wallet
		 */
		payWith: RequiredParams<'wallet'>
		/**
		 * o​r
		 */
		or: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d
		 */
		connectFailed: string
	}
	manual: {
		/**
		 * O​r​ ​t​r​a​n​s​f​e​r​ ​m​a​n​u​a​l​l​y
		 */
		heading: string
		/**
		 * S​e​n​d​ ​{​a​m​o​u​n​t​}​ ​{​a​s​s​e​t​}​ ​o​n​ ​{​c​h​a​i​n​}​ ​t​o​:
		 * @param {unknown} amount
		 * @param {unknown} asset
		 * @param {unknown} chain
		 */
		sendTo: RequiredParams<'amount' | 'asset' | 'chain'>
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d
		 */
		copied: string
		/**
		 * S​e​n​d​ ​f​r​o​m​ ​a​n​y​ ​w​a​l​l​e​t​ ​o​r​ ​e​x​c​h​a​n​g​e​,​ ​t​h​e​n​ ​c​l​i​c​k​ ​"​I​'​v​e​ ​s​e​n​t​ ​i​t​ ​m​a​n​u​a​l​l​y​"​ ​—​ ​t​h​e​ ​s​c​a​n​n​e​r​ ​d​e​t​e​c​t​s​ ​t​h​e​ ​i​n​b​o​u​n​d​ ​t​r​a​n​s​f​e​r​ ​t​h​e​ ​s​a​m​e​ ​w​a​y​.
		 */
		hint: string
		/**
		 * m​a​n​u​a​l​ ​t​r​a​n​s​f​e​r​ ​c​o​n​f​i​r​m​e​d
		 */
		done: string
	}
	apiKey: {
		/**
		 * A​P​I​ ​K​e​y
		 */
		label: string
		/**
		 * P​a​s​t​e​ ​y​o​u​r​ ​s​a​n​d​b​o​x​ ​A​P​I​ ​k​e​y​ ​(​s​k​_​s​a​n​d​b​o​x​_​…​)
		 */
		placeholder: string
		/**
		 * U​s​e​ ​a​ ​s​a​n​d​b​o​x​ ​k​e​y​.​ ​I​t​ ​s​t​a​y​s​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r​ ​a​n​d​ ​i​s​ ​s​e​n​t​ ​d​i​r​e​c​t​l​y​ ​t​o​ ​t​h​e​ ​A​P​I​.​ ​I​n​ ​p​r​o​d​u​c​t​i​o​n​,​ ​c​a​l​l​ ​t​h​e​ ​A​P​I​ ​f​r​o​m​ ​y​o​u​r​ ​b​a​c​k​e​n​d​,​ ​n​o​t​ ​t​h​e​ ​b​r​o​w​s​e​r​.
		 */
		hint: string
	}
	amountMode: {
		/**
		 * A​m​o​u​n​t​ ​m​o​d​e
		 */
		label: string
		/**
		 * E​X​A​C​T
		 */
		exact: string
		/**
		 * A​U​T​O
		 */
		auto: string
		/**
		 * E​x​a​c​t​ ​=​ ​u​s​e​ ​t​h​e​ ​e​x​a​c​t​ ​a​m​o​u​n​t​ ​y​o​u​ ​e​n​t​e​r​;​ ​A​u​t​o​ ​=​ ​s​y​s​t​e​m​ ​a​d​j​u​s​t​s​ ​a​m​o​u​n​t​ ​w​i​t​h​i​n​ ​a​ ​t​i​n​y​ ​r​a​n​g​e​ ​t​o​ ​a​v​o​i​d​ ​a​d​d​r​e​s​s​ ​c​o​n​f​l​i​c​t​s​ ​o​n​ ​s​h​a​r​e​d​ ​a​d​d​r​e​s​s​e​s​.
		 */
		hint: string
	}
	autoImport: {
		/**
		 * A​u​t​o​-​i​m​p​o​r​t​ ​s​a​n​d​b​o​x​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s
		 */
		label: string
		/**
		 * W​h​e​n​ ​o​n​,​ ​a​ ​d​e​t​e​r​m​i​n​i​s​t​i​c​ ​b​u​r​n​e​r​ ​s​a​n​d​b​o​x​ ​a​d​d​r​e​s​s​ ​i​s​ ​i​m​p​o​r​t​e​d​ ​f​o​r​ ​t​h​i​s​ ​o​r​d​e​r​ ​b​e​f​o​r​e​ ​c​r​e​a​t​i​n​g​ ​i​t​ ​—​ ​u​s​e​f​u​l​ ​w​h​e​n​ ​y​o​u​r​ ​o​r​g​ ​h​a​s​ ​n​o​ ​a​d​d​r​e​s​s​e​s​ ​y​e​t​.​ ​T​u​r​n​ ​i​t​ ​o​f​f​ ​i​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​u​s​e​ ​o​n​l​y​ ​t​h​e​ ​a​d​d​r​e​s​s​e​s​ ​y​o​u​ ​m​a​n​a​g​e​ ​y​o​u​r​s​e​l​f​.
		 */
		hint: string
	}
	noAddress: {
		/**
		 * t​i​p​:​ ​i​f​ ​t​h​i​s​ ​f​a​i​l​e​d​ ​b​e​c​a​u​s​e​ ​y​o​u​r​ ​o​r​g​ ​h​a​s​ ​n​o​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s​,​ ​e​n​a​b​l​e​ ​A​u​t​o​-​i​m​p​o​r​t​ ​a​b​o​v​e​ ​o​r​ ​c​r​e​a​t​e​ ​o​n​e​ ​i​n​ ​D​a​s​h​b​o​a​r​d​ ​→​ ​A​d​d​r​e​s​s​e​s​.
		 */
		hint: string
	}
	network: {
		/**
		 * A​u​t​o
		 */
		auto: string
	}
	/**
	 * ,​ 
	 */
	sep: string
	chains: {
		/**
		 * C​h​a​i​n​s​ ​(​m​u​l​t​i​-​s​e​l​e​c​t​)
		 */
		label: string
		/**
		 * S​e​l​e​c​t​ ​c​h​a​i​n​s​…
		 */
		placeholder: string
	}
	faucet: {
		/**
		 * R​e​a​l​ ​w​a​l​l​e​t​ ​t​r​a​n​s​a​c​t​i​o​n​ ​o​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​t​e​s​t​n​e​t​(​s​)​ ​—​ ​d​o​ ​n​o​t​ ​u​s​e​ ​m​a​i​n​n​e​t​ ​f​u​n​d​s​.​ ​G​e​t​ ​t​e​s​t​ ​f​u​n​d​s​:​ 
		 */
		prefix: string
	}
	dropped: {
		/**
		 * T​R​O​N​ ​a​n​d​ ​S​o​l​a​n​a​ ​a​r​e​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​p​a​i​d​ ​p​l​a​n​s​.​ ​P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​E​V​M​ ​c​h​a​i​n​s​.
		 */
		nonEvmOnly: string
		/**
		 * T​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​h​a​i​n​s​ ​a​r​e​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​p​a​i​d​ ​p​l​a​n​s​.​ ​P​l​e​a​s​e​ ​d​e​s​e​l​e​c​t​:​ ​{​c​h​a​i​n​s​}
		 * @param {unknown} chains
		 */
		nonEvmMix: RequiredParams<'chains'>
		/**
		 * E​n​a​b​l​e​ ​A​u​t​o​-​i​m​p​o​r​t​ ​o​r​ ​c​o​n​f​i​g​u​r​e​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s​e​s​ ​i​n​ ​t​h​e​ ​D​a​s​h​b​o​a​r​d​.
		 */
		fallback: string
	}
	status: {
		/**
		 * e​n​t​e​r​ ​a​n​ ​A​P​I​ ​k​e​y​ ​f​i​r​s​t
		 */
		missingKey: string
		/**
		 * p​o​l​l​i​n​g​ ​{​t​a​r​g​e​t​}​…​ ​(​u​p​ ​t​o​ ​{​s​e​c​o​n​d​s​}​s​)
		 * @param {unknown} seconds
		 * @param {unknown} target
		 */
		polling: RequiredParams<'seconds' | 'target'>
		/**
		 * o​r​d​e​r​=​{​s​t​a​t​u​s​}
		 * @param {unknown} status
		 */
		orderStatus: RequiredParams<'status'>
		/**
		 * t​i​m​e​o​u​t​ ​w​a​i​t​i​n​g​ ​f​o​r​ ​{​t​a​r​g​e​t​}​;​ ​s​c​a​n​n​e​r​ ​m​a​y​ ​s​t​i​l​l​ ​b​e​ ​c​a​t​c​h​i​n​g​ ​u​p
		 * @param {unknown} target
		 */
		timeout: RequiredParams<'target'>
		/**
		 * w​a​l​l​e​t​ ​p​r​o​v​i​d​e​r​ ​n​o​t​ ​f​o​u​n​d
		 */
		walletProviderNotFound: string
		/**
		 * w​a​i​t​i​n​g​ ​f​o​r​ ​w​a​l​l​e​t​ ​c​o​n​f​i​r​m​a​t​i​o​n​…
		 */
		waitingWallet: string
		/**
		 * t​x​ ​{​h​a​s​h​}
		 * @param {unknown} hash
		 */
		txHash: RequiredParams<'hash'>
		/**
		 * V​i​e​w​ ​o​n​ ​b​l​o​c​k​ ​e​x​p​l​o​r​e​r​ ​↗
		 */
		viewTx: string
		/**
		 * o​r​d​e​r​ ​r​e​a​c​h​e​d​ ​{​s​t​a​t​u​s​}​ ​b​e​f​o​r​e​ ​{​t​a​r​g​e​t​}
		 * @param {unknown} status
		 * @param {unknown} target
		 */
		terminalStatus: RequiredParams<'status' | 'target'>
		/**
		 * t​r​a​n​s​a​c​t​i​o​n​ ​r​e​v​e​r​t​e​d​ ​o​n​ ​c​h​a​i​n​;​ ​n​o​ ​t​o​k​e​n​s​ ​w​e​r​e​ ​m​o​v​e​d
		 */
		walletReverted: string
	}
	log: {
		/**
		 * c​r​e​a​t​e​ ​f​a​i​l​e​d​:​ ​A​P​I​ ​k​e​y​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		missingKey: string
		/**
		 * c​r​e​a​t​e​ ​f​a​i​l​e​d​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		createFailed: RequiredParams<'error'>
		/**
		 * o​r​d​e​r​ ​{​i​d​}​ ​c​r​e​a​t​e​d​ ​(​{​s​t​a​t​u​s​}​)
		 * @param {unknown} id
		 * @param {unknown} status
		 */
		orderCreated: RequiredParams<'id' | 'status'>
		/**
		 * r​e​f​r​e​s​h​ ​f​a​i​l​e​d​:​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		refreshFailed: RequiredParams<'error'>
		/**
		 * o​r​d​e​r​ ​s​t​a​t​u​s​:​ ​{​s​t​a​t​u​s​}
		 * @param {unknown} status
		 */
		orderStatus: RequiredParams<'status'>
		/**
		 * w​a​l​l​e​t​ ​p​a​y​m​e​n​t​ ​s​e​n​t​:​ ​{​h​a​s​h​}
		 * @param {unknown} hash
		 */
		walletSent: RequiredParams<'hash'>
		/**
		 * w​a​l​l​e​t​ ​p​a​y​m​e​n​t​ ​f​a​i​l​e​d​:​ ​{​m​e​s​s​a​g​e​}
		 * @param {unknown} message
		 */
		walletFailed: RequiredParams<'message'>
		/**
		 * t​r​a​n​s​a​c​t​i​o​n​ ​r​e​v​e​r​t​e​d​:​ ​{​h​a​s​h​}
		 * @param {unknown} hash
		 */
		walletReverted: RequiredParams<'hash'>
		/**
		 * w​a​l​l​e​t​ ​p​r​o​v​i​d​e​r​ ​n​o​t​ ​f​o​u​n​d​ ​f​o​r​ ​{​c​h​a​i​n​}
		 * @param {unknown} chain
		 */
		providerNotFound: RequiredParams<'chain'>
		/**
		 * w​a​i​t​ ​{​t​a​r​g​e​t​}​ ​t​i​m​e​d​ ​o​u​t​;​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
		 * @param {unknown} target
		 */
		waitTimedOut: RequiredParams<'target'>
		/**
		 * w​a​i​t​ ​{​t​a​r​g​e​t​}​ ​s​t​o​p​p​e​d​:​ ​o​r​d​e​r​ ​s​t​a​t​u​s​ ​i​s​ ​{​s​t​a​t​u​s​}
		 * @param {unknown} status
		 * @param {unknown} target
		 */
		waitTerminalStatus: RequiredParams<'status' | 'target'>
		/**
		 * m​a​n​u​a​l​ ​t​r​a​n​s​f​e​r​ ​c​o​n​f​i​r​m​e​d​;​ ​p​o​l​l​i​n​g​ ​f​o​r​ ​o​n​-​c​h​a​i​n​ ​d​e​t​e​c​t​i​o​n
		 */
		manualConfirmed: string
	}
	/**
	 * T​h​i​s​ ​p​l​a​y​g​r​o​u​n​d​ ​c​a​l​l​s​ ​<​c​o​d​e​>​@​s​t​a​b​l​e​o​p​s​/​a​p​i​-​s​d​k​<​/​c​o​d​e​>​ ​d​i​r​e​c​t​l​y​ ​f​r​o​m​ ​y​o​u​r​ ​b​r​o​w​s​e​r​ ​w​i​t​h​ ​t​h​e​ ​A​P​I​ ​k​e​y​ ​y​o​u​ ​p​r​o​v​i​d​e​.​ ​S​t​e​p​ ​2​ ​c​a​l​l​s​ ​<​c​o​d​e​>​@​s​t​a​b​l​e​o​p​s​/​w​a​l​l​e​t​-​s​d​k​<​/​c​o​d​e​>​ ​t​o​ ​a​s​k​ ​t​h​e​ ​b​r​o​w​s​e​r​ ​w​a​l​l​e​t​ ​t​o​ ​s​e​n​d​ ​a​ ​r​e​a​l​ ​t​e​s​t​n​e​t​ ​t​r​a​n​s​a​c​t​i​o​n​ ​—​ ​o​r​ ​y​o​u​ ​c​a​n​ ​s​k​i​p​ ​t​h​e​ ​w​a​l​l​e​t​,​ ​t​r​a​n​s​f​e​r​ ​t​o​ ​t​h​e​ ​s​h​o​w​n​ ​a​d​d​r​e​s​s​ ​f​r​o​m​ ​a​n​y​ ​w​a​l​l​e​t​/​e​x​c​h​a​n​g​e​,​ ​a​n​d​ ​c​l​i​c​k​ ​"​I​'​v​e​ ​s​e​n​t​ ​i​t​ ​m​a​n​u​a​l​l​y​"​.​ ​O​r​d​e​r​s​ ​a​d​v​a​n​c​e​ ​t​o​ ​d​e​t​e​c​t​e​d​ ​/​ ​c​o​n​f​i​r​m​e​d​ ​/​ ​f​i​n​a​l​i​z​e​d​ ​v​i​a​ ​t​h​e​ ​s​c​a​n​n​e​r​ ​a​n​d​ ​c​o​n​f​i​r​m​a​t​i​o​n​s​ ​w​a​t​c​h​e​r​.​ ​I​n​ ​s​a​n​d​b​o​x​ ​(​t​e​s​t​n​e​t​)​,​ ​i​f​ ​y​o​u​r​ ​o​r​g​ ​h​a​s​ ​n​o​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s​ ​y​e​t​,​ ​o​n​e​ ​i​s​ ​a​u​t​o​-​c​r​e​a​t​e​d​ ​f​o​r​ ​t​h​i​s​ ​o​r​d​e​r​.​ ​U​s​e​ ​a​ ​s​a​n​d​b​o​x​ ​k​e​y​ ​o​n​l​y​ ​—​ ​n​e​v​e​r​ ​p​a​s​t​e​ ​a​ ​l​i​v​e​ ​k​e​y​ ​i​n​t​o​ ​a​ ​b​r​o​w​s​e​r​.​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​g​i​t​l​a​b​.​c​o​m​/​S​t​a​b​l​e​O​p​s​/​s​t​a​b​l​e​o​p​s​-​p​l​a​y​g​r​o​u​n​d​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​r​e​f​e​r​r​e​r​"​ ​c​l​a​s​s​=​"​u​n​d​e​r​l​i​n​e​ ​u​n​d​e​r​l​i​n​e​-​o​f​f​s​e​t​-​2​"​>​V​i​e​w​ ​s​o​u​r​c​e​ ​o​n​ ​G​i​t​L​a​b​<​/​a​>​.
	 */
	footer: string
	checkout: {
		/**
		 * A​P​I​ ​K​e​y
		 */
		apiKey: string
		/**
		 * P​a​s​t​e​ ​y​o​u​r​ ​s​a​n​d​b​o​x​ ​A​P​I​ ​k​e​y​ ​(​s​k​_​s​a​n​d​b​o​x​_​…​)
		 */
		apiKeyPlaceholder: string
		/**
		 * F​o​r​ ​d​o​c​s​ ​t​e​s​t​i​n​g​ ​o​n​l​y​.​ ​T​h​e​ ​k​e​y​ ​s​t​a​y​s​ ​i​n​ ​t​h​i​s​ ​b​r​o​w​s​e​r​.​ ​C​r​e​a​t​e​ ​C​h​e​c​k​o​u​t​ ​S​e​s​s​i​o​n​s​ ​o​n​ ​y​o​u​r​ ​b​a​c​k​e​n​d​ ​i​n​ ​p​r​o​d​u​c​t​i​o​n​.
		 */
		apiKeyHint: string
		/**
		 * M​e​r​c​h​a​n​t​ ​o​r​d​e​r​ ​I​D
		 */
		merchantOrderId: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * C​h​a​i​n​s​ ​a​n​d​ ​a​s​s​e​t​s​ ​(​m​u​l​t​i​-​s​e​l​e​c​t​)
		 */
		chainAsset: string
		/**
		 * S​e​l​e​c​t​ ​o​n​e​ ​o​r​ ​m​o​r​e​ ​c​h​a​i​n​s​…
		 */
		chainPlaceholder: string
		/**
		 * A​m​o​u​n​t​ ​m​o​d​e
		 */
		amountMode: string
		/**
		 * E​X​A​C​T
		 */
		amountModeExact: string
		/**
		 * A​U​T​O
		 */
		amountModeAuto: string
		/**
		 * C​h​e​c​k​o​u​t​ ​t​i​t​l​e
		 */
		title: string
		/**
		 * C​h​e​c​k​o​u​t​ ​d​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * S​u​c​c​e​s​s​ ​U​R​L
		 */
		successUrl: string
		/**
		 * C​a​n​c​e​l​ ​U​R​L
		 */
		cancelUrl: string
		/**
		 * O​r​d​e​r​ ​m​e​t​a​d​a​t​a
		 */
		metadata: string
		/**
		 * A​u​t​o​-​i​m​p​o​r​t​ ​s​a​n​d​b​o​x​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s
		 */
		autoImport: string
		/**
		 * W​h​e​n​ ​o​n​,​ ​a​ ​d​e​t​e​r​m​i​n​i​s​t​i​c​ ​b​u​r​n​e​r​ ​s​a​n​d​b​o​x​ ​a​d​d​r​e​s​s​ ​i​s​ ​i​m​p​o​r​t​e​d​ ​f​o​r​ ​t​h​i​s​ ​o​r​d​e​r​ ​b​e​f​o​r​e​ ​t​h​e​ ​s​e​s​s​i​o​n​ ​i​s​ ​c​r​e​a​t​e​d​.​ ​U​s​e​f​u​l​ ​w​h​e​n​ ​y​o​u​r​ ​o​r​g​ ​h​a​s​ ​n​o​ ​a​d​d​r​e​s​s​e​s​ ​y​e​t​.​ ​T​u​r​n​ ​i​t​ ​o​f​f​ ​t​o​ ​u​s​e​ ​o​n​l​y​ ​t​h​e​ ​a​d​d​r​e​s​s​e​s​ ​y​o​u​ ​m​a​n​a​g​e​ ​y​o​u​r​s​e​l​f​.
		 */
		autoImportHint: string
		/**
		 * t​i​p​:​ ​i​f​ ​t​h​i​s​ ​f​a​i​l​e​d​ ​b​e​c​a​u​s​e​ ​y​o​u​r​ ​o​r​g​ ​h​a​s​ ​n​o​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s​,​ ​e​n​a​b​l​e​ ​A​u​t​o​-​i​m​p​o​r​t​ ​a​b​o​v​e​ ​o​r​ ​c​r​e​a​t​e​ ​o​n​e​ ​i​n​ ​D​a​s​h​b​o​a​r​d​ ​→​ ​A​d​d​r​e​s​s​e​s​.
		 */
		noAddressHint: string
		/**
		 * T​R​O​N​ ​a​n​d​ ​S​o​l​a​n​a​ ​a​r​e​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​p​a​i​d​ ​p​l​a​n​s​.​ ​P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​E​V​M​ ​c​h​a​i​n​s​.
		 */
		droppedNonEvmOnly: string
		/**
		 * T​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​h​a​i​n​s​ ​a​r​e​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​p​a​i​d​ ​p​l​a​n​s​.​ ​P​l​e​a​s​e​ ​d​e​s​e​l​e​c​t​:​ ​{​c​h​a​i​n​s​}
		 * @param {unknown} chains
		 */
		droppedNonEvmMix: RequiredParams<'chains'>
		/**
		 * E​n​a​b​l​e​ ​A​u​t​o​-​i​m​p​o​r​t​ ​o​r​ ​c​o​n​f​i​g​u​r​e​ ​r​e​c​e​i​v​i​n​g​ ​a​d​d​r​e​s​s​e​s​ ​i​n​ ​t​h​e​ ​D​a​s​h​b​o​a​r​d​.
		 */
		droppedFallback: string
		/**
		 * C​r​e​a​t​e​ ​a​n​d​ ​o​p​e​n​ ​C​h​e​c​k​o​u​t
		 */
		create: string
		/**
		 * N​e​w​ ​m​e​r​c​h​a​n​t​ ​o​r​d​e​r​ ​I​D
		 */
		newOrderId: string
		/**
		 * E​n​t​e​r​ ​a​ ​s​a​n​d​b​o​x​ ​A​P​I​ ​k​e​y​,​ ​m​e​r​c​h​a​n​t​ ​o​r​d​e​r​ ​I​D​,​ ​a​n​d​ ​a​m​o​u​n​t​.
		 */
		missingRequired: string
		/**
		 * S​e​l​e​c​t​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​c​h​a​i​n​.
		 */
		missingChain: string
		/**
		 * m​e​t​a​d​a​t​a​ ​m​u​s​t​ ​b​e​ ​a​ ​J​S​O​N​ ​o​b​j​e​c​t
		 */
		metadataObjectError: string
		/**
		 * c​h​e​c​k​o​u​t​ ​s​e​s​s​i​o​n​ ​r​e​s​p​o​n​s​e​ ​i​s​ ​m​i​s​s​i​n​g​ ​c​l​i​e​n​t​_​s​e​c​r​e​t
		 */
		responseMissingSecret: string
		/**
		 * u​n​k​n​o​w​n​ ​e​r​r​o​r
		 */
		unknownError: string
	}
}

export type TranslationFunctions = {
	steps: {
		/**
		 * 1. Create payment order
		 */
		create: () => LocalizedString
		/**
		 * 2. Pay with wallet on-chain
		 */
		pay: () => LocalizedString
		/**
		 * 3. Wait detected
		 */
		waitDetected: () => LocalizedString
		/**
		 * 4. Wait confirmed
		 */
		waitConfirmed: () => LocalizedString
		/**
		 * 5. Wait finalized
		 */
		waitFinalized: () => LocalizedString
	}
	actions: {
		/**
		 * Creating…
		 */
		creating: () => LocalizedString
		/**
		 * 1. Create order
		 */
		createOrder: () => LocalizedString
		/**
		 * Open browser wallet…
		 */
		paying: () => LocalizedString
		/**
		 * 2. Browser wallet
		 */
		pay: () => LocalizedString
		/**
		 * 2. I've sent it manually
		 */
		confirmManual: () => LocalizedString
		/**
		 * Polling…
		 */
		polling: () => LocalizedString
		/**
		 * 3. Wait detected
		 */
		waitDetected: () => LocalizedString
		/**
		 * 4. Wait confirmed
		 */
		waitConfirmed: () => LocalizedString
		/**
		 * 5. Wait finalized
		 */
		waitFinalized: () => LocalizedString
		/**
		 * Reset
		 */
		reset: () => LocalizedString
	}
	walletConnect: {
		/**
		 * 2. Mobile wallet
		 */
		button: () => LocalizedString
		/**
		 * Pay with a mobile wallet
		 */
		heading: () => LocalizedString
		/**
		 * Mobile wallet pay is disabled because no Reown projectId was provided.
		 */
		missingProjectId: () => LocalizedString
		/**
		 * Mobile wallet pay is only available for EVM payment instructions.
		 */
		noEvm: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Payment QR code
		 */
		qrAlt: () => LocalizedString
		/**
		 * Your wallet did not authorize {chains}. Go back and reconnect, then select the requested network in your wallet.
		 */
		chainNotAuthorized: (arg: { chains: unknown }) => LocalizedString
		/**
		 * Copy link
		 */
		copyUri: () => LocalizedString
		/**
		 * Open {wallet}
		 */
		openWallet: (arg: { wallet: unknown }) => LocalizedString
		/**
		 * Scan with {wallet} on your phone
		 */
		scanWithWallet: (arg: { wallet: unknown }) => LocalizedString
		/**
		 * Scan with any mobile wallet
		 */
		scanAnyWallet: () => LocalizedString
		/**
		 * Pay with {wallet}
		 */
		payWith: (arg: { wallet: unknown }) => LocalizedString
		/**
		 * or
		 */
		or: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Connection failed
		 */
		connectFailed: () => LocalizedString
	}
	manual: {
		/**
		 * Or transfer manually
		 */
		heading: () => LocalizedString
		/**
		 * Send {amount} {asset} on {chain} to:
		 */
		sendTo: (arg: { amount: unknown, asset: unknown, chain: unknown }) => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied
		 */
		copied: () => LocalizedString
		/**
		 * Send from any wallet or exchange, then click "I've sent it manually" — the scanner detects the inbound transfer the same way.
		 */
		hint: () => LocalizedString
		/**
		 * manual transfer confirmed
		 */
		done: () => LocalizedString
	}
	apiKey: {
		/**
		 * API Key
		 */
		label: () => LocalizedString
		/**
		 * Paste your sandbox API key (sk_sandbox_…)
		 */
		placeholder: () => LocalizedString
		/**
		 * Use a sandbox key. It stays in your browser and is sent directly to the API. In production, call the API from your backend, not the browser.
		 */
		hint: () => LocalizedString
	}
	amountMode: {
		/**
		 * Amount mode
		 */
		label: () => LocalizedString
		/**
		 * EXACT
		 */
		exact: () => LocalizedString
		/**
		 * AUTO
		 */
		auto: () => LocalizedString
		/**
		 * Exact = use the exact amount you enter; Auto = system adjusts amount within a tiny range to avoid address conflicts on shared addresses.
		 */
		hint: () => LocalizedString
	}
	autoImport: {
		/**
		 * Auto-import sandbox receiving address
		 */
		label: () => LocalizedString
		/**
		 * When on, a deterministic burner sandbox address is imported for this order before creating it — useful when your org has no addresses yet. Turn it off if you want to use only the addresses you manage yourself.
		 */
		hint: () => LocalizedString
	}
	noAddress: {
		/**
		 * tip: if this failed because your org has no receiving address, enable Auto-import above or create one in Dashboard → Addresses.
		 */
		hint: () => LocalizedString
	}
	network: {
		/**
		 * Auto
		 */
		auto: () => LocalizedString
	}
	/**
	 * , 
	 */
	sep: () => LocalizedString
	chains: {
		/**
		 * Chains (multi-select)
		 */
		label: () => LocalizedString
		/**
		 * Select chains…
		 */
		placeholder: () => LocalizedString
	}
	faucet: {
		/**
		 * Real wallet transaction on the selected testnet(s) — do not use mainnet funds. Get test funds: 
		 */
		prefix: () => LocalizedString
	}
	dropped: {
		/**
		 * TRON and Solana are only available on paid plans. Please select EVM chains.
		 */
		nonEvmOnly: () => LocalizedString
		/**
		 * The following chains are only available on paid plans. Please deselect: {chains}
		 */
		nonEvmMix: (arg: { chains: unknown }) => LocalizedString
		/**
		 * Enable Auto-import or configure receiving addresses in the Dashboard.
		 */
		fallback: () => LocalizedString
	}
	status: {
		/**
		 * enter an API key first
		 */
		missingKey: () => LocalizedString
		/**
		 * polling {target}… (up to {seconds}s)
		 */
		polling: (arg: { seconds: unknown, target: unknown }) => LocalizedString
		/**
		 * order={status}
		 */
		orderStatus: (arg: { status: unknown }) => LocalizedString
		/**
		 * timeout waiting for {target}; scanner may still be catching up
		 */
		timeout: (arg: { target: unknown }) => LocalizedString
		/**
		 * wallet provider not found
		 */
		walletProviderNotFound: () => LocalizedString
		/**
		 * waiting for wallet confirmation…
		 */
		waitingWallet: () => LocalizedString
		/**
		 * tx {hash}
		 */
		txHash: (arg: { hash: unknown }) => LocalizedString
		/**
		 * View on block explorer ↗
		 */
		viewTx: () => LocalizedString
		/**
		 * order reached {status} before {target}
		 */
		terminalStatus: (arg: { status: unknown, target: unknown }) => LocalizedString
		/**
		 * transaction reverted on chain; no tokens were moved
		 */
		walletReverted: () => LocalizedString
	}
	log: {
		/**
		 * create failed: API key is required
		 */
		missingKey: () => LocalizedString
		/**
		 * create failed: {error}
		 */
		createFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * order {id} created ({status})
		 */
		orderCreated: (arg: { id: unknown, status: unknown }) => LocalizedString
		/**
		 * refresh failed: {error}
		 */
		refreshFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * order status: {status}
		 */
		orderStatus: (arg: { status: unknown }) => LocalizedString
		/**
		 * wallet payment sent: {hash}
		 */
		walletSent: (arg: { hash: unknown }) => LocalizedString
		/**
		 * wallet payment failed: {message}
		 */
		walletFailed: (arg: { message: unknown }) => LocalizedString
		/**
		 * transaction reverted: {hash}
		 */
		walletReverted: (arg: { hash: unknown }) => LocalizedString
		/**
		 * wallet provider not found for {chain}
		 */
		providerNotFound: (arg: { chain: unknown }) => LocalizedString
		/**
		 * wait {target} timed out; try again later
		 */
		waitTimedOut: (arg: { target: unknown }) => LocalizedString
		/**
		 * wait {target} stopped: order status is {status}
		 */
		waitTerminalStatus: (arg: { status: unknown, target: unknown }) => LocalizedString
		/**
		 * manual transfer confirmed; polling for on-chain detection
		 */
		manualConfirmed: () => LocalizedString
	}
	/**
	 * This playground calls <code>@stableops/api-sdk</code> directly from your browser with the API key you provide. Step 2 calls <code>@stableops/wallet-sdk</code> to ask the browser wallet to send a real testnet transaction — or you can skip the wallet, transfer to the shown address from any wallet/exchange, and click "I've sent it manually". Orders advance to detected / confirmed / finalized via the scanner and confirmations watcher. In sandbox (testnet), if your org has no receiving address yet, one is auto-created for this order. Use a sandbox key only — never paste a live key into a browser. <a href="https://gitlab.com/StableOps/stableops-playground" target="_blank" rel="noreferrer" class="underline underline-offset-2">View source on GitLab</a>.
	 */
	footer: () => LocalizedString
	checkout: {
		/**
		 * API Key
		 */
		apiKey: () => LocalizedString
		/**
		 * Paste your sandbox API key (sk_sandbox_…)
		 */
		apiKeyPlaceholder: () => LocalizedString
		/**
		 * For docs testing only. The key stays in this browser. Create Checkout Sessions on your backend in production.
		 */
		apiKeyHint: () => LocalizedString
		/**
		 * Merchant order ID
		 */
		merchantOrderId: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * Chains and assets (multi-select)
		 */
		chainAsset: () => LocalizedString
		/**
		 * Select one or more chains…
		 */
		chainPlaceholder: () => LocalizedString
		/**
		 * Amount mode
		 */
		amountMode: () => LocalizedString
		/**
		 * EXACT
		 */
		amountModeExact: () => LocalizedString
		/**
		 * AUTO
		 */
		amountModeAuto: () => LocalizedString
		/**
		 * Checkout title
		 */
		title: () => LocalizedString
		/**
		 * Checkout description
		 */
		description: () => LocalizedString
		/**
		 * Success URL
		 */
		successUrl: () => LocalizedString
		/**
		 * Cancel URL
		 */
		cancelUrl: () => LocalizedString
		/**
		 * Order metadata
		 */
		metadata: () => LocalizedString
		/**
		 * Auto-import sandbox receiving address
		 */
		autoImport: () => LocalizedString
		/**
		 * When on, a deterministic burner sandbox address is imported for this order before the session is created. Useful when your org has no addresses yet. Turn it off to use only the addresses you manage yourself.
		 */
		autoImportHint: () => LocalizedString
		/**
		 * tip: if this failed because your org has no receiving address, enable Auto-import above or create one in Dashboard → Addresses.
		 */
		noAddressHint: () => LocalizedString
		/**
		 * TRON and Solana are only available on paid plans. Please select EVM chains.
		 */
		droppedNonEvmOnly: () => LocalizedString
		/**
		 * The following chains are only available on paid plans. Please deselect: {chains}
		 */
		droppedNonEvmMix: (arg: { chains: unknown }) => LocalizedString
		/**
		 * Enable Auto-import or configure receiving addresses in the Dashboard.
		 */
		droppedFallback: () => LocalizedString
		/**
		 * Create and open Checkout
		 */
		create: () => LocalizedString
		/**
		 * New merchant order ID
		 */
		newOrderId: () => LocalizedString
		/**
		 * Enter a sandbox API key, merchant order ID, and amount.
		 */
		missingRequired: () => LocalizedString
		/**
		 * Select at least one chain.
		 */
		missingChain: () => LocalizedString
		/**
		 * metadata must be a JSON object
		 */
		metadataObjectError: () => LocalizedString
		/**
		 * checkout session response is missing client_secret
		 */
		responseMissingSecret: () => LocalizedString
		/**
		 * unknown error
		 */
		unknownError: () => LocalizedString
	}
}

export type Formatters = {}
